name: TypeScript Test

on:
  push:
    branches:
      - "**" # This will trigger the workflow on every push to any branch
  pull_request:

permissions:
  contents: read

jobs:
  lint:
    name: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "20.x"
          registry-url: "https://registry.npmjs.org"
      - name: Run npm ci
        run: npm ci
      - name: Run tests
        run: npm run test
